name: release Windows desktop (Avalonia UI)

on:
  workflow_dispatch:
    inputs:
      release_tag:
        required: false
        type: string
  push:
    branches:
      - master
    tags:
      - 'v*'
      - 'V*'
      - '[0-9]*'

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      target: windows
      project: ./v2rayN.Desktop/v2rayN.Desktop.csproj

  release-zip:
    if: inputs.release_tag != '' || (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/'))
    needs: build
    uses: ./.github/workflows/package-zip.yml
    with:
      target: windows-desktop
      release_tag: ${{ github.event.inputs.release_tag || github.ref_name }}
